<?php

return [
    'color_accent' => ['required', 'string', 'max:7'],
    'color_accent_secondary' => ['required', 'string', 'max:7'],
    'hero_slogan' => ['nullable', 'string', 'max:500'],
    'hero_image' => ['nullable', 'string', 'max:255'],
    'show_section_shop' => ['nullable', 'in:0,1'],
    'show_section_vote' => ['nullable', 'in:0,1'],
    'trailer_url' => ['nullable', 'url', 'max:255'],
    'hero_video_enabled' => ['required', 'in:0,1'],
    'discord_server_id' => ['nullable', 'string', 'max:32', 'regex:/^\d*$/'],
    'footer_discord' => ['nullable', 'string', 'max:255'],
    'footer_twitter' => ['nullable', 'string', 'max:255'],
    'staff_1_name' => ['nullable', 'string', 'max:32'],
    'staff_1_role' => ['nullable', 'string', 'max:64'],
    'staff_1_link' => ['nullable', 'url', 'max:255'],
    'staff_2_name' => ['nullable', 'string', 'max:32'],
    'staff_2_role' => ['nullable', 'string', 'max:64'],
    'staff_2_link' => ['nullable', 'url', 'max:255'],
    'staff_3_name' => ['nullable', 'string', 'max:32'],
    'staff_3_role' => ['nullable', 'string', 'max:64'],
    'staff_3_link' => ['nullable', 'url', 'max:255'],
    'staff_4_name' => ['nullable', 'string', 'max:32'],
    'staff_4_role' => ['nullable', 'string', 'max:64'],
    'staff_4_link' => ['nullable', 'url', 'max:255'],
    'staff_5_name' => ['nullable', 'string', 'max:32'],
    'staff_5_role' => ['nullable', 'string', 'max:64'],
    'staff_5_link' => ['nullable', 'url', 'max:255'],
    'staff_6_name' => ['nullable', 'string', 'max:32'],
    'staff_6_role' => ['nullable', 'string', 'max:64'],
    'staff_6_link' => ['nullable', 'url', 'max:255'],
    'staff_7_name' => ['nullable', 'string', 'max:32'],
    'staff_7_role' => ['nullable', 'string', 'max:64'],
    'staff_7_link' => ['nullable', 'url', 'max:255'],
    'staff_8_name' => ['nullable', 'string', 'max:32'],
    'staff_8_role' => ['nullable', 'string', 'max:64'],
    'staff_8_link' => ['nullable', 'url', 'max:255'],
    'home_layout' => ['nullable', 'json', 'max:5000'],
    'server_ip_display' => ['nullable', 'string', 'max:255'],
];
